version: '3.2'

services:
  letsencrypt:
    image: eu.gcr.io/k8-discovery-185615/docker-letsencrypt 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLATFORM_GCLOUD_VERSION: "${PLATFORM_GCLOUD_VERSION}"
        PLATFORM_KUBECTL_VERSION: "${PLATFORM_KUBECTL_VERSION}"
    volumes:
      - ./scripts:/app
      - ./hooks:/usr/local/bin/dehydrated/hooks
    environment:
      - CONTACT_EMAIL 
      - FQDN
